package com.vinner.codeme.projecteuler;

import com.vinner.codeme.ProblemStatement;

public class EvenFibonacci implements ProblemStatement {


    // BruteForce
    public long getSumOfEvenNumbers(long max)
    {
        long sum=2; //Since 2 is Already even
        int prev = 1;
        int next=2;
       // System.out.print(prev + "," + next+",");
        int nextNum =  prev + next;
        while(nextNum < max)
        {

            prev = next;
            next = nextNum;
            if(nextNum % 2 == 0)
                sum+=nextNum;
          //  System.out.print(nextNum+",");
            nextNum =  prev + next;
        }
        return sum;
    }

    @Override
    public String getDescription() {
        return "public final String description = \"Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:\\n\" +\n" +
                "            \"\\n\" +\n" +
                "            \"1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...\\n\" +\n" +
                "            \"\\n\" +\n" +
                "            \"By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.\";";
    }

    @Override
    public String getSolutionNotes() {
        return null;
    }

   /* public static void main (String args[])
    {
        EvenFibonacci ef = new EvenFibonacci();

    }*/
}
